name: 1-minute-cron
on:
  schedule:
    - cron: '*/1 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --url 'https://algotuno-web3.vercel.app/api/welcome' \
          --header 'Authorization: Bearer ${{ secrets.NEXT_PUBLIC_API_SECRET_KEY }}'